coverage:
  status:
    project:
      default:
        threshold: 100%
    patch:
      default:
        threshold: 100%
  ignore:
    - manage.py
    - eduquiz/settings.py
    - **/apps.py
    - **/tests.py
    - **/wsgi.py
