notifications:
  email: false

# code language
language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements_coverage.txt

# command to run tests
script:
  - coverage run --source='.' manage.py test

# command to run after success
after_success:
  - codecov
